### ISSUE TITLE
Rozdziały

### ISSUE THREAD

**Issue by xingyin123** [Szymoek02/LNU-odpowiedzi#1]
Szymek mam prośbę mógłbyś dodać odpowiedzi z rozdziałów: proces kompilacji; wyrażenia, operatory, warunki; instrukcje sterujące i pętle z c++ p.podstawowy. Byłabym wdzięczna

**Comment by szymon-s292** [comment]
Już załatwione. Przepraszam za braki daj znać jakby czegoś jeszcze nie
było. 😁

śr., 14 lut 2024 o 19:51 xingyin123 ***@***.***> napisał(a):

**Comment by xingyin123** [comment]
Hej, coś mi się nie zgadza z twoim rozwiązaniem kiedy wpisuje go u siebie zadanie jest błędne. To zadanie to Obiekty wewnątrz obiektu w Strukturach danych w p. rozszerzonym w C++.

**Comment by xingyin123** [comment]
niestety nadal to samo
![Zrzut ekranu_25-2-2024_13592_edu t-lem com](https://github.com/Szymoek02/LNU-odpowiedzi/assets/159160293/80005a5a-22cc-42c7-82c8-ca6479d3ae05)

**Comment by xingyin123** [comment]
Mimo iż poprawiłeś to zadanie parę godzin temu nadal jest coś źle. Proszę popraw. Jestem tobie bardzo wdzięczna za te starania itp.

**Comment by szymon-s292** [comment]
Ej ale wiesz że ja właśnie też nie wiem o co z tym chodzi. Pisałem do nich
i wysłali mi w odpowiedzi rozwiązanie ale to nadal nie działa.
Nawet jak napisze
bool find(int n)
{
    return true;
}

void emplace(int n)
{

}

Dosłownie nawet jak zostawi się te funkcję puste byle żeby się odpaliło to
nadal ten błąd jest. Sory ale ja serio nie ogarniam o co tam chodzi 😔
pt., 1 mar 2024, 18:04 użytkownik xingyin123 ***@***.***>
napisał:

**Comment by xingyin123** [comment]
I tak ci dziękuję za twoje starania

**Comment by xingyin123** [comment]
cześć wrzucisz misje z lnu, ewentualnie przygotowanie do matury -  python, prosze. Wiele ci zawdzięczam

**Comment by xingyin123** [comment]
cześć przesyłam ci zadanie z pythona p.rozszerzony ćwiczenie: odchylenie
def deviation( readings ):
    avg=sum(readings)/len(readings)
    for i in readings:
        print(f"{i-avg:o=25}")
![Zrzut ekranu_22-3-2024_16929_edu t-lem com](https://github.com/Szymoek02/LNU-odpowiedzi/assets/159160293/38ac7a21-ec62-40d1-8712-c3bca20f81e5)

**Comment by xingyin123** [comment]
nawiązując do przedostatniego komentarza jeszcze raz proszę cię o pomoc
